// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMUlkpUUqXf27T-rWa1KfGbrFK2wd0Wew',
    appId: '1:1031185131099:web:4465713bfc2d7d458b817e',
    messagingSenderId: '1031185131099',
    projectId: 'elgamalfinancial',
    authDomain: 'elgamalfinancial.firebaseapp.com',
    databaseURL: 'https://elgamalfinancial-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'elgamalfinancial.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA0SrFJL9rHtT8M44LX53HxsAPCm7v0mQ',
    appId: '1:1031185131099:android:fb8bf7b8f6f322868b817e',
    messagingSenderId: '1031185131099',
    projectId: 'elgamalfinancial',
    databaseURL: 'https://elgamalfinancial-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'elgamalfinancial.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI_7fwMC0QrdBjx-5vVB3cDe-4NE_KzPI',
    appId: '1:1031185131099:ios:37dac8f7f43716958b817e',
    messagingSenderId: '1031185131099',
    projectId: 'elgamalfinancial',
    databaseURL: 'https://elgamalfinancial-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'elgamalfinancial.firebasestorage.app',
    iosBundleId: 'com.example.moneytrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI_7fwMC0QrdBjx-5vVB3cDe-4NE_KzPI',
    appId: '1:1031185131099:ios:37dac8f7f43716958b817e',
    messagingSenderId: '1031185131099',
    projectId: 'elgamalfinancial',
    databaseURL: 'https://elgamalfinancial-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'elgamalfinancial.firebasestorage.app',
    iosBundleId: 'com.example.moneytrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMUlkpUUqXf27T-rWa1KfGbrFK2wd0Wew',
    appId: '1:1031185131099:web:0a36707de30fadc28b817e',
    messagingSenderId: '1031185131099',
    projectId: 'elgamalfinancial',
    authDomain: 'elgamalfinancial.firebaseapp.com',
    databaseURL: 'https://elgamalfinancial-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'elgamalfinancial.firebasestorage.app',
  );

}